USE call_nest;

CREATE TABLE IF NOT EXISTS integration_event_outbox (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  integration_app_id BIGINT UNSIGNED NOT NULL,
  topic VARCHAR(80) NOT NULL,
  idempotency_key VARCHAR(191) NOT NULL,
  target_url VARCHAR(1024) NOT NULL,
  payload_json JSON NOT NULL,
  status ENUM('pending', 'processing', 'delivered', 'failed', 'dead') NOT NULL DEFAULT 'pending',
  attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
  max_attempts INT UNSIGNED NOT NULL DEFAULT 8,
  next_attempt_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_attempt_at TIMESTAMP NULL DEFAULT NULL,
  last_error TEXT NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  deleted_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_integration_outbox_idempotency (tenant_id, integration_app_id, idempotency_key),
  INDEX idx_integration_outbox_ready (tenant_id, status, next_attempt_at, deleted_at),
  INDEX idx_integration_outbox_tenant_id (tenant_id, id),
  CONSTRAINT fk_integration_outbox_app FOREIGN KEY (integration_app_id) REFERENCES integration_apps(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS integration_webhook_deliveries (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  integration_app_id BIGINT UNSIGNED NOT NULL,
  outbox_id BIGINT UNSIGNED NULL,
  topic VARCHAR(80) NOT NULL,
  idempotency_key VARCHAR(191) NOT NULL,
  request_url VARCHAR(1024) NOT NULL,
  request_headers_json JSON NULL,
  request_body_json JSON NULL,
  response_status INT NULL,
  response_body_text TEXT NULL,
  latency_ms INT UNSIGNED NULL,
  delivery_status ENUM('success', 'failed') NOT NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  deleted_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id),
  INDEX idx_integration_deliveries_lookup (tenant_id, integration_app_id, created_at, deleted_at),
  INDEX idx_integration_deliveries_idempotency (tenant_id, integration_app_id, idempotency_key),
  INDEX idx_integration_deliveries_tenant_id (tenant_id, id),
  CONSTRAINT fk_integration_deliveries_app FOREIGN KEY (integration_app_id) REFERENCES integration_apps(id),
  CONSTRAINT fk_integration_deliveries_outbox FOREIGN KEY (outbox_id) REFERENCES integration_event_outbox(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tenant_billing_usage_daily (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id BIGINT UNSIGNED NOT NULL,
  usage_date DATE NOT NULL,
  metric_key VARCHAR(80) NOT NULL,
  metric_value BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  deleted_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_tenant_usage_metric_daily (tenant_id, usage_date, metric_key),
  INDEX idx_tenant_usage_date (tenant_id, usage_date, deleted_at),
  INDEX idx_tenant_usage_tenant_id (tenant_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
